wikidue_uat/backend/src/main/java/com/e7learning/product/form/ProductForm.java

package com.e7learning.product.form;

import java.util.Date;

import org.apache.commons.lang.StringUtils;
import org.springframework.format.annotation.DateTimeFormat;

import com.e7learning.common.form.BaseForm;
import com.e7learning.repository.model.Product;

/**
 * @author J
 * 
 * 商品管理
 */
public class ProductForm extends BaseForm<Product>{

	/**
	 * 商品PK
	 */
	private String pkProduct;
	/**
	 * 教具PK
	 */
	private String pkProps;
	/**
	 * 課程PK
	 */
	private String pkCourse;
	/**
	 * 營隊PK
	 */
	private String pkCamp;
	/**
	 * 商品名稱
	 */
	private String productName;
	/**
	 * 商品數量
	 */
	private String quantity;
	/**
	 * 上架日期
	 */
	@DateTimeFormat(pattern = "yyyy/MM/dd")
	private Date publishSDate;
	/**
	 * 下架日期
	 */
	@DateTimeFormat(pattern = "yyyy/MM/dd")
	private Date publishEDate;
	/**
	 * 原價
	 */
	private String price;
	/**
	 * 售價
	 */
	private String discountPrice;
	
	/**
	 * 啟用
	 */
	private String  active;
	
	/**
	 * 分類類型
	 */
	private String categoryType;
	
	/**
	 * 廠商名稱
	 */
	private String vendorName;
	/**
	 * 廠商代號
	 */
	private String pkVendor;
	
	/**
	 * 修改頁面是否唯讀
	 */
	private boolean isPageReadonly;
	
	private boolean isSdateReadonly;
	
	/**
	 * 正在上架
	 */
	private boolean onMarket;
	
	/**
	 * 排序權重
	 */
	private String weights;
	
	
	public ProductForm() {
	}


	public String getPkProduct() {
		return pkProduct;
	}


	public void setPkProduct(String pkProduct) {
		this.pkProduct = pkProduct;
	}



	public String getProductName() {
		return productName;
	}


	public void setProductName(String productName) {
		this.productName = productName;
	}


	public String getQuantity() {
		return quantity;
	}


	public void setQuantity(String quantity) {
		this.quantity = quantity;
	}


	public Date getPublishSDate() {
		return publishSDate;
	}


	public void setPublishSDate(Date publishSDate) {
		this.publishSDate = publishSDate;
	}


	public Date getPublishEDate() {
		return publishEDate;
	}


	public void setPublishEDate(Date publishEDate) {
		this.publishEDate = publishEDate;
	}


	public String getDiscountPrice() {
		return discountPrice;
	}


	public void setDiscountPrice(String discountPrice) {
		this.discountPrice = discountPrice;
	}


	public String getPrice() {
		return price;
	}


	public void setPrice(String price) {
		this.price = price;
	}


	public String getActive() {
		return active;
	}


	public void setActive(String active) {
		this.active = active;
	}
	
	public String getCategoryType() {
		return categoryType;
	}


	public void setCategoryType(String categoryType) {
		this.categoryType = categoryType;
	}
	


	public String getPkProps() {
		return pkProps;
	}


	public void setPkProps(String pkProps) {
		this.pkProps = pkProps;
	}


	public String getPkCourse() {
		return pkCourse;
	}


	public void setPkCourse(String pkCourse) {
		this.pkCourse = pkCourse;
	}


	public String getPkCamp() {
		return pkCamp;
	}


	public void setPkCamp(String pkCamp) {
		this.pkCamp = pkCamp;
	}


	public String getVendorName() {
		return vendorName;
	}


	public void setVendorName(String vendorName) {
		this.vendorName = vendorName;
	}


	public String getPkVendor() {
		return pkVendor;
	}

	public void setPkVendor(String pkVendor) {
		this.pkVendor = pkVendor;
	}


	public boolean isPageReadonly() {
		return isPageReadonly;
	}


	public void setPageReadonly(boolean isPageReadonly) {
		this.isPageReadonly = isPageReadonly;
	}


	public boolean isSdateReadonly() {
		return isSdateReadonly;
	}

	public void setSdateReadonly(boolean isSdateReadonly) {
		this.isSdateReadonly = isSdateReadonly;
	}


	public boolean isOnMarket() {
		return onMarket;
	}


	public void setOnMarket(boolean onMarket) {
		this.onMarket = onMarket;
	}


	public String getWeights() {
		return weights;
	}


	public void setWeights(String weights) {
		this.weights = weights;
	}
	
}

wikidue_uat/backend/src/main/java/com/e7learning/product/controller/ProductController.java
package com.e7learning.product.controller;

import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import org.apache.commons.beanutils.BeanUtils;
import org.apache.commons.lang3.StringUtils;
import org.apache.log4j.Logger;
import org.displaytag.tags.TableTagParameters;
import org.displaytag.util.ParamEncoder;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.WebDataBinder;
import org.springframework.web.bind.annotation.InitBinder;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.SessionAttributes;

import com.e7learning.common.controller.BaseController;
import com.e7learning.common.exception.ServiceException;
import com.e7learning.common.service.ConfigService;
import com.e7learning.common.utils.CommonUtils;
import com.e7learning.product.form.ProductForm;
import com.e7learning.product.service.ProductService;
import com.e7learning.product.validation.ProductFormValidation;
import com.e7learning.repository.model.Product;

/**
 * @author J
 *
 */
@Controller
@RequestMapping(value = "/product")
@SessionAttributes(ProductController.FORM_BEAN_NAME)
public class ProductController extends BaseController {

	private static final Logger log = Logger.getLogger(ProductController.class);

	public static final String FORM_BEAN_NAME = "productForm";
	
	private static final String QUERY_PAGE = "queryProductPage";

	private static final String ADD_PAGE = "addProductPage";
	
	private static final String EDIT_PAGE = "editProductPage";

	@Autowired
	private ProductFormValidation productFormValidation;
	
	@Autowired
	private ProductService productService ;
	
	@Autowired
	private ConfigService configService;
	
	@InitBinder(ProductController.FORM_BEAN_NAME)
	protected void initBinder(WebDataBinder binder, HttpSession session) {
		binder.setValidator(productFormValidation);
	}
	
	@RequestMapping(value = "/query", method = { RequestMethod.GET })
	public String goQuery(Model model) {
		ProductForm form = new ProductForm();
		try {
			form.setResult(productService.queryProduct(form, 1));
		} catch (ServiceException e) {
			
		}
		model.addAttribute(FORM_BEAN_NAME, form);
		return QUERY_PAGE;
	}

	@RequestMapping(value = "/query", params = "method=query")
	public String query(HttpServletRequest request, ProductForm form, Model model) {
		String pageName = new ParamEncoder("list").encodeParameterName(TableTagParameters.PARAMETER_PAGE);
		int nextPage = getPage(request.getParameter(pageName));
		try {
			form.setResult(productService.queryProduct(form, nextPage));
		} catch (ServiceException e) {
			
		}
		return QUERY_PAGE;
	}
	
	@RequestMapping(value = "/add", method = { RequestMethod.GET })
	public String goAdd(Model model) {
		ProductForm form = new ProductForm();
		// 預設排序權重
		form.setWeights(configService.getWeights());
		model.addAttribute(FORM_BEAN_NAME, form);
		return ADD_PAGE;
	}

	@RequestMapping(params = "method=save", value = "/add", method = { RequestMethod.POST })
	public String add(@Validated ProductForm form, BindingResult result) {
		if (result.hasErrors()) {
			return ADD_PAGE;
		}
		try {
			productService.addProduct(form);
			return "redirect:/product/query?method=query";
		} catch (ServiceException e) {
			
		}
		return ADD_PAGE;
	}
	
	@RequestMapping(params = "method=remove", value = "/remove", method = { RequestMethod.POST })
	public String remove(ProductForm form, Model model) {
		if(StringUtils.isNotBlank(form.getPkProduct() )) {
			Product product = productService.findByPkProduct(form.getPkProduct());
			if(product != null) {
				try {
					productService.remove(product.getPkProduct());
					return "redirect:/product/query?method=query";
				} catch (ServiceException e) {
					// 避免display tag 查詢request發生405錯誤
					form.setResult(null);
					model.addAttribute(FORM_BEAN_NAME, form);
				}
			}
		}
		return QUERY_PAGE;
	}
	
	@RequestMapping(value = "/modify", method = { RequestMethod.POST })
	public String goModify(Model model, ProductForm form) {
		if(StringUtils.isNotBlank(form.getPkProduct() )) {
			Product product = productService.findByPkProduct(form.getPkProduct());
			try {
				BeanUtils.copyProperties(form, product);
				// 顯示props數量
				if(product.getProps() != null) {
					form.setQuantity(product.getProps().getQuantity()+"");
					form.setCategoryType("PROPS");
				}else if(product.getCourse() != null) {
					form.setCategoryType("COURSE");
				}
				setProductFormStatus(form, product);
			} catch (Exception e) {
				e.printStackTrace();
			}
			model.addAttribute(FORM_BEAN_NAME, form);
		}
		return EDIT_PAGE;
	}
	
	@RequestMapping(params = "method=modify", value = "/modify", method = { RequestMethod.POST })
	public String modify(@Validated ProductForm form,BindingResult result) {
		if (result.hasErrors()) {
			return EDIT_PAGE;
		}
		try {
			productService.saveProduct(form);
			return "redirect:/product/query?method=query";
		} catch (ServiceException e) {
			
		}
		return EDIT_PAGE;
	}
	
	@RequestMapping(params = "method=update",value = "/updateTag", method = { RequestMethod.POST })
	public String updateTag(Model model, ProductForm form) {
		if(StringUtils.isNotBlank(form.getPkProduct() )) {
			Product product = productService.findByPkProduct(form.getPkProduct());
			try {
				BeanUtils.copyProperties(form, product);
				setProductFormStatus(form, product);
				productService.updateProductTag(product);
			} catch (Exception e) {
				e.printStackTrace();
			}
			model.addAttribute(FORM_BEAN_NAME, form);
		}
		return EDIT_PAGE;
	}
	
	private void setProductFormStatus(ProductForm form,Product product) {
		Date today = CommonUtils.getTodayWithoutTimes();
		if(product.getPublishSDate().compareTo(today) < 0) {
			form.setSdateReadonly(true);
		}else {
			form.setSdateReadonly(false);
		}
		if(product.getPublishEDate().compareTo(today) < 0 ) {
			form.setPageReadonly(true);
		}else {
			form.setPageReadonly(false);
		}
		if(product.getProps() != null) {
			form.setPkProps(product.getProps().getPkProps().toString());
		}else if(product.getCourse() != null) {
			form.setPkCourse(product.getCourse().getPkCourse().toString());
		}else if(product.getCamp() != null) {
			form.setPkCamp(product.getCamp().getPkCamp().toString());
		}
	}
	
}

wikidue_uat/backend/src/main/webapp/WEB-INF/views/product/productAdd.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<%@ taglib uri="http://displaytag.sf.net" prefix="display"%>
<%@ taglib uri="http://www.springframework.org/security/tags"
	prefix="sec"%>
<%@ taglib prefix="e7" uri="/WEB-INF/tld/e7.tld"%>
<%@ taglib prefix="sessionConversation"
	uri="/WEB-INF/tld/sessionConversation.tld"%>
<%@ taglib uri="http://www.springframework.org/tags" prefix="spring"%>
<!-- 預覽上傳的圖片 -->
<script
	src="${pageContext.request.contextPath}/plugins/uploadPreview/jquery.uploadPreview.js?v=<spring:eval expression="@configService.applicationVersion" />"></script>

<script type="text/javascript">
	$(function() {
		$('.datepicker').datepicker({
			format : 'yyyy/mm/dd',
			autoclose : true,
			todayBtn : true,
			todayHighlight : true
		});
		if ($("#categoryType").val() == "COURSE") {
			$("#qtyDiv").hide();
		}
	});
	function addProduct() {
		$.LoadingOverlay("show");
		setTimeout(function() {
			$("#productForm").submit();
		}, 500);
	}
	function goQuery() {
		$.LoadingOverlay("show");
	}
	function chooseProps() {

		$.fancybox({
			'autoSize' : false,
			'fitToView' : false,
			'width' : "100%",
			'scrolling' : 'auto',
			'transitionIn' : 'none',
			'transitionOut' : 'none',
			'type' : 'iframe',
			'padding' : '0',
			'closeBtn' : true,
			'href' : '${pageContext.request.contextPath}/props/queryProps?t='
					+ new Date().getTime()
		});
	}
	function chooseCourse() {

		$.fancybox({
			'autoSize' : false,
			'fitToView' : false,
			'width' : "100%",
			'scrolling' : 'auto',
			'transitionIn' : 'none',
			'transitionOut' : 'none',
			'type' : 'iframe',
			'padding' : '0',
			'closeBtn' : true,
			'href' : '${pageContext.request.contextPath}/course/queryCourse?t='
					+ new Date().getTime()
		});
	}
	function showProps(pkProps, productName, price, discountPrice, quantity) {
		clearErrors(); 
		$("#categoryType").val("PROPS");
		$("#pkProps").val(pkProps);
		$("#pkCourse").val("");
		$("#productName").val(productName);
		$("#price").val(price);
		$("#discountPrice").val(discountPrice);
		$("#quantity").val(quantity);
		$("#qtyDiv").show();
	}
	function showCourse(pkCourse, productName, price, discountPrice) {
		clearErrors(); 
		$("#categoryType").val("COURSE");
		$("#pkCourse").val(pkCourse);
		$("#pkProps").val("");
		$("#productName").val(productName);
		$("#price").val(price);
		$("#discountPrice").val(discountPrice);
		$("#quantity").val("");
		$("#qtyDiv").hide();
	}
	function clearErrors(){
		$('span[id*="error"]').text('');
	}
</script>
<div class="row">
	<div class="col-md-12">
		<div class="box box-primary">
			<form:form modelAttribute="productForm" name="productForm"
				action="${pageContext.request.contextPath}/product/add"
				method="post" enctype="multipart/form-data" class="form-horizontal">
				<sessionConversation:insertSessionConversationId
					attributeName="productForm" />
				<form:hidden path="method" value="save" />
				<form:hidden path="pkProduct" />
				<form:hidden path="pkCourse" />
				<form:hidden path="pkProps" />
				<form:hidden path="categoryType" />
				<div class="box-body">
					<div class="form-group">
						<label for="name" class="col-sm-2 control-label">*選擇商品</label>
						<div class="col-sm-10">
							<button type="button"
								onclick="chooseCourse('COURSE');return false;"
								class="btn btn-info">選擇課程</button>
							<button type="button"
								onclick="chooseProps('PROPS');return false;"
								class="btn btn-info">選擇教具</button>
						</div>
					</div>
					<div class="form-group">
						<label for="productName" class="col-sm-2 control-label">*商品名稱</label>
						<div class="col-sm-10">
							<form:input path="productName" class="form-control"
								placeholder="商品名稱" maxlength="5" readonly="true" />
							<form:errors path="productName" class="text-red" />
						</div>
					</div>
					<div class="form-group" id="qtyDiv">
						<label for="quantity" class="col-sm-2 control-label">*商品數量</label>
						<div class="col-sm-10">
							<form:input path="quantity" class="form-control"
								placeholder="商品數量" maxlength="5" readonly="true" />
							<form:errors path="quantity" class="text-red" />
						</div>
					</div>
					<div class="form-group">
						<label for="price" class="col-sm-2 control-label">原價</label>
						<div class="col-sm-10">
							<form:input path="price" class="form-control" maxlength="8"
								placeholder="原價" />
							<form:errors path="price" class="text-red" />
						</div>
					</div>
					<div class="form-group">
						<label for="discountPrice" class="col-sm-2 control-label">優惠價</label>
						<div class="col-sm-10">
							<form:input path="discountPrice" class="form-control"
								maxlength="8" placeholder="優惠價" />
							<form:errors path="discountPrice" class="text-red" />
						</div>
					</div>
					<div class="form-group date">
						<label for="publishSDate" class="col-sm-2 control-label">*上架日期</label>
						<div class="col-sm-10">
							<div class="input-group date">
								<div class="input-group-addon"
									onclick="$('#publishSDate').focus()">
									<i class="fa fa-calendar"></i>
								</div>
								<form:input path="publishSDate"
									cssClass="form-control pull-right  datepicker"
									placeholder="yyyy/MM/dd" maxlength="10" />
								<form:errors path="publishSDate" class="text-red" />
							</div>
						</div>
					</div>
					<div class="form-group">
						<label for="publishEDate" class="col-sm-2 control-label">*下架日期</label>
						<div class="col-sm-10">
							<div class="input-group date">
								<div class="input-group-addon"
									onclick="$('#publishEDate').focus()">
									<i class="fa fa-calendar"></i>
								</div>
								<form:input path="publishEDate"
									cssClass="form-control pull-right  datepicker"
									placeholder="yyyy/MM/dd" maxlength="10" />
								<form:errors path="publishEDate" class="text-red" />
							</div>
						</div>
					</div>
					<c:if test="${user_auth.admin}">
						<div class="form-group">
							<label for="weights" class="col-sm-2 control-label">排序權重</label>
							<div class="col-sm-10">
								<form:input path="weights" class="form-control" maxlength="4"
									placeholder="請輸入0~9999(含)之間的數字" />
								<form:errors path="weights" class="text-red" />
							</div>
						</div>
					</c:if>
					<div class="form-group">
						<label for="active" class="col-sm-2 control-label">啟用</label>
						<div class="col-sm-10">
							<form:radiobutton path="active" id="radio1" value="1"
								checked="checked" />
							<label for="radio1">是</label><br />
							<form:radiobutton path="active" id="radio2" value="0" />
							<label for="radio2">否</label>
						</div>
					</div>
				</div>
				<!-- /.box-body -->
				<div class="box-footer">
					<button type="button" onclick="addProduct()" class="btn btn-info">儲存</button>
					<a href="${pageContext.request.contextPath}/product/query#result"
						class="btn btn-default pull-right" onclick="goQuery();">取消</a>
				</div>
				<!-- /.box-footer -->
			</form:form>

			<!-- /.box-body -->
		</div>
		<!-- /.box -->
	</div>
</div>

wikidue_uat/backend/src/main/webapp/WEB-INF/views/product/productModify.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<%@ taglib uri="http://displaytag.sf.net" prefix="display"%>
<%@ taglib uri="http://www.springframework.org/security/tags"
	prefix="sec"%>
<%@ taglib prefix="e7" uri="/WEB-INF/tld/e7.tld"%>
<%@ taglib prefix="sessionConversation"
	uri="/WEB-INF/tld/sessionConversation.tld"%>
<%@ taglib uri="http://www.springframework.org/tags" prefix="spring" %>
<!-- 預覽上傳的圖片 -->
<script
	src="${pageContext.request.contextPath}/plugins/uploadPreview/jquery.uploadPreview.js?v=<spring:eval expression="@configService.applicationVersion" />"></script>

<script type="text/javascript">
	$(function() {
		$('.datepicker').datepicker({
			format : 'yyyy/mm/dd',
			autoclose : true,
			todayBtn : true,
			todayHighlight : true
		});
		if ($("#categoryType").val() == "COURSE") {
			$("#qtyDiv").hide();
		}
		$('.datepicker').datepicker("option", "disabled", true);
	});
	function modifyProduct() {
		$.LoadingOverlay("show");
        setTimeout(function(){
        	$("#productForm").submit();
        }, 500);
	}
	function goQuery() {
		$.LoadingOverlay("show");
	}
	function updateTag() {
		document.productForm.action = '${pageContext.request.contextPath}/product/updateTag';
		$("#method").val("update");
		$.LoadingOverlay("show");
        setTimeout(function(){
        	$("#productForm").submit();
        }, 500);
	}
	function chooseProps() {
		$.fancybox({
			'autoSize' : false,
			'fitToView' : false,
			'width' : "100%",
			'scrolling' : 'auto',
			'transitionIn' : 'none',
			'transitionOut' : 'none',
			'type' : 'iframe',
			'padding' : '0',
			'closeBtn' : true,
			'href' : '${pageContext.request.contextPath}/props/queryProps'
		});
	}
	function chooseCourse() {
		$.fancybox({
			'autoSize' : false,
			'fitToView' : false,
			'width' : "100%",
			'scrolling' : 'auto',
			'transitionIn' : 'none',
			'transitionOut' : 'none',
			'type' : 'iframe',
			'padding' : '0',
			'closeBtn' : true,
			'href' : '${pageContext.request.contextPath}/course/queryCourse'
		});
	}
	function showProps(pkProps, productName, price, discountPrice, quantity) {
		clearErrors();
		$("#categoryType").val("PROPS");
		$("#pkProps").val(pkProps);
		$("#pkCourse").val("");
		$("#productName").val(productName);
		$("#price").val(price);
		$("#discountPrice").val(discountPrice);
		$("#quantity").val(quantity);
		$("#qtyDiv").show();
	}
	function showCourse(pkCourse, productName, price, discountPrice) {
		clearErrors();
		$("#categoryType").val("COURSE");
		$("#pkCourse").val(pkCourse);
		$("#pkProps").val("");
		$("#productName").val(productName);
		$("#price").val(price);
		$("#discountPrice").val(discountPrice);
		$("#quantity").val("");
		$("#qtyDiv").hide();
	}
	function clearErrors(){
		$('span[id*="error"]').text('');
	}
</script>
<div class="row">
	<div class="col-md-12">
		<div class="box box-primary">
			<form:form modelAttribute="productForm" name="productForm"
				action="${pageContext.request.contextPath}/product/modify"
				method="post" enctype="multipart/form-data" class="form-horizontal">
				<sessionConversation:insertSessionConversationId
					attributeName="productForm" />
				<form:hidden path="method" value="modify" />
				<form:hidden path="pkProduct" />
				<form:hidden path="pkCourse" />
				<form:hidden path="pkProps" />
				<form:hidden path="categoryType" />
				<div class="box-body">
					<%-- 
					<div class="form-group">
						<label for="name" class="col-sm-2 control-label">*選擇商品</label>
						<div class="col-sm-10">
							<button type="button" onclick="chooseCourse('COURSE');return false;" class="btn btn-info" disabled>選擇課程</button>
							<button type="button" onclick="chooseProps('PROPS');return false;" class="btn btn-info" disabled>選擇教具</button>
						</div>
					</div>
				--%>
					<div class="form-group">
						<label for="name" class="col-sm-2 control-label">更新商品標韱</label>
						<div class="col-sm-10">
							<button type="button" onclick="updateTag()"
								class="btn btn-warning">更新</button>
						</div>
					</div>
					<div class="form-group">
						<label for="productName" class="col-sm-2 control-label">*商品名稱</label>
						<div class="col-sm-10">
							<form:input path="productName" class="form-control"
								placeholder="商品名稱" maxlength="5" readonly="true" />
							<form:errors path="productName" class="text-red" />
						</div>
					</div>
					<c:if test="${not empty productForm.pkProps }">
						<div class="form-group" id="qtyDiv">
							<label for="quantity" class="col-sm-2 control-label">*商品數量</label>
							<div class="col-sm-10">
								<form:input path="quantity" class="form-control"
									placeholder="商品數量" maxlength="5" readonly="true" />
								<form:errors path="quantity" class="text-red" />
							</div>
						</div>
					</c:if>
					<div class="form-group">
						<label for="price" class="col-sm-2 control-label">*原價</label>
						<div class="col-sm-10">
							<c:if test="${not productForm.pageReadonly}">
								<form:input path="price" class="form-control" maxlength="8"
									placeholder="原價" />
							</c:if>
							<c:if test="${productForm.pageReadonly}">
								<form:input path="price" class="form-control" maxlength="8"
									placeholder="原價" readonly="true" />
							</c:if>
							<form:errors path="price" class="text-red" />
						</div>
					</div>
					<div class="form-group">
						<label for="discountPrice" class="col-sm-2 control-label">*優惠價</label>
						<div class="col-sm-10">
							<c:if test="${not productForm.pageReadonly}">
								<form:input path="discountPrice" class="form-control"
									maxlength="8" placeholder="優惠價" />
							</c:if>
							<c:if test="${productForm.pageReadonly}">
								<form:input path="discountPrice" class="form-control"
									maxlength="8" placeholder="優惠價" readonly="true" />
							</c:if>
							<form:errors path="discountPrice" class="text-red" />
						</div>
					</div>
					<div class="form-group date">
						<label for="publishSDate" class="col-sm-2 control-label">*上架日期</label>
						<div class="col-sm-10">
							<div class="input-group date">
								<div class="input-group-addon"
									onclick="$('#publishSDate').focus()">
									<i class="fa fa-calendar"></i>
								</div>
								<c:if test="${productForm.sdateReadonly }">
									<form:input path="publishSDate"
										cssClass="form-control pull-right " readonly="true"
										placeholder="yyyy/MM/dd" maxlength="10" />
								</c:if>
								<c:if test="${not productForm.sdateReadonly }">
									<form:input path="publishSDate"
										cssClass="form-control pull-right  datepicker"
										placeholder="yyyy/MM/dd" maxlength="10" />
								</c:if>
								<form:errors path="publishSDate" class="text-red" />
							</div>
						</div>
					</div>
					<div class="form-group">
						<label for="publishEDate" class="col-sm-2 control-label">*下架日期</label>
						<div class="col-sm-10">
							<div class="input-group date">
								<div class="input-group-addon"
									onclick="$('#publishEDate').focus()">
									<i class="fa fa-calendar"></i>
								</div>
								<c:if test="${not productForm.pageReadonly}">
									<form:input path="publishEDate"
										cssClass="form-control pull-right  datepicker"
										placeholder="yyyy/MM/dd" maxlength="10" />
								</c:if>
								<c:if test="${productForm.pageReadonly}">
									<form:input path="publishEDate"
										cssClass="form-control pull-right  datepicker"
										placeholder="yyyy/MM/dd" maxlength="10" readonly="true" />
								</c:if>
								<form:errors path="publishEDate" class="text-red" />
							</div>
						</div>
					</div>
					<c:if test="${user_auth.admin}">
					<div class="form-group">
						<label for="weights" class="col-sm-2 control-label">*排序權重</label>
						<div class="col-sm-10">
							<form:input path="weights" class="form-control" maxlength="4"
								placeholder="請輸入0~9999(含)之間的數字" />
							<form:errors path="weights" class="text-red" />
						</div>
					</div>
					</c:if>
					<div class="form-group">
						<label for="active" class="col-sm-2 control-label">啟用</label>
						<div class="col-sm-10">
							<form:radiobutton path="active" id="radio1" value="1"
								checked="checked" />
							<label for="radio1">是</label><br />
							<form:radiobutton path="active" id="radio2" value="0" />
							<label for="radio2">否</label>
						</div>
					</div>
				</div>
				<!-- /.box-body -->
				<div class="box-footer">
					<c:if test="${ productForm.pageReadonly}">
						<button type="button" onclick="modifyProduct()"
							class="btn btn-info" disabled>儲存</button>
					</c:if>
					<c:if test="${not productForm.pageReadonly}">
						<button type="button" onclick="modifyProduct()"
							class="btn btn-info">儲存</button>
					</c:if>
					<a href="${pageContext.request.contextPath}/product/query#result"
						class="btn btn-default pull-right" onclick="goQuery();">取消</a>
				</div>
				<!-- /.box-footer -->
			</form:form>

			<!-- /.box-body -->
		</div>
		<!-- /.box -->
	</div>
</div>